create table city (id bigint not null auto_increment, city varchar(255), status integer, primary key (id)) engine=InnoDB;
create table inventory (id bigint not null auto_increment, description varchar(255) not null, name varchar(45) not null, quantity_output integer not null, quantity_stock integer not null, serial_number varchar(255) not null, status integer not null, unit_price bigint not null, primary key (id)) engine=InnoDB;
create table province (id bigint not null auto_increment, name varchar(255), status integer, primary key (id)) engine=InnoDB;
create table role (id bigint not null auto_increment, name varchar(255), status integer, primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, document_number varchar(255), document_type integer, email varchar(255), last_name varchar(255), name varchar(255), password varchar(255), status integer, telephone bigint, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table users_roles add constraint FKt4v0rrweyk393bdgt107vdx0x foreign key (role_id) references role (id);
alter table users_roles add constraint FKgd3iendaoyh04b95ykqise6qh foreign key (user_id) references user (id);
create table city (id bigint not null auto_increment, city varchar(255), status integer, primary key (id)) engine=InnoDB;
create table inventory (id bigint not null auto_increment, description varchar(255) not null, name varchar(45) not null, quantity_output integer not null, quantity_stock integer not null, serial_number varchar(255) not null, status integer not null, unit_price bigint not null, primary key (id)) engine=InnoDB;
create table province (id bigint not null auto_increment, name varchar(255), status integer, primary key (id)) engine=InnoDB;
create table role (id bigint not null auto_increment, name varchar(255), status integer, primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, document_number varchar(255), document_type integer, email varchar(255), last_name varchar(255), name varchar(255), password varchar(255), status integer, telephone bigint, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table users_roles add constraint FKt4v0rrweyk393bdgt107vdx0x foreign key (role_id) references role (id);
alter table users_roles add constraint FKgd3iendaoyh04b95ykqise6qh foreign key (user_id) references user (id);
create table city (id bigint not null auto_increment, city varchar(255), status integer, primary key (id)) engine=InnoDB;
create table inventory (id bigint not null auto_increment, description varchar(255) not null, name varchar(45) not null, quantity_output integer not null, quantity_stock integer not null, serial_number varchar(255) not null, status integer not null, unit_price bigint not null, primary key (id)) engine=InnoDB;
create table province (id bigint not null auto_increment, name varchar(255), status integer, primary key (id)) engine=InnoDB;
create table role (id bigint not null auto_increment, name varchar(255), status integer, primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, document_number varchar(255), document_type integer, email varchar(255), last_name varchar(255), name varchar(255), password varchar(255), status integer, telephone bigint, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table users_roles add constraint FKt4v0rrweyk393bdgt107vdx0x foreign key (role_id) references role (id);
alter table users_roles add constraint FKgd3iendaoyh04b95ykqise6qh foreign key (user_id) references user (id);
create table city (id bigint not null auto_increment, city varchar(255), status integer, primary key (id)) engine=InnoDB;
create table inventory (id bigint not null auto_increment, description varchar(255) not null, name varchar(45) not null, quantity_output integer not null, quantity_stock integer not null, serial_number varchar(255) not null, status integer not null, unit_price bigint not null, primary key (id)) engine=InnoDB;
create table province (id bigint not null auto_increment, name varchar(255), status integer, primary key (id)) engine=InnoDB;
create table role (id bigint not null auto_increment, name varchar(255), status integer, primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, document_number varchar(255), document_type integer, email varchar(255), last_name varchar(255), name varchar(255), password varchar(255), status integer, telephone bigint, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table users_roles add constraint FKt4v0rrweyk393bdgt107vdx0x foreign key (role_id) references role (id);
alter table users_roles add constraint FKgd3iendaoyh04b95ykqise6qh foreign key (user_id) references user (id);
